server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mypj?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 10
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /sms
    username: carry
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
file:
  uploadPath: .\data\evidence\
